import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="content_wrapper">
				<header>
					<h1>ROTTEN PEPPERS</h1>
				</header>

				<main>
					<div className="movie_cover">
						<h2>SINGULARITY</h2>
						<Image src="/wallpaperflare.com_wallpaper.jpg" width={640} height={420} alt="Mobie Cover" />
					</div>
				</main>

				<footer>
					<h5>ROTTEN PEPPERS!</h5>
					<p>Submit your movie rating</p>
				</footer>
			</div>
		</>
	);
}
